Update patch set 1
Patch Set 1:

Then you need to help me. Why do I get:

hardware/qcom/display-caf/msm8998/libqdutils/../libqdutils/display_config.h:53:24: error: use of undeclared identifier 'HWC_DISPLAY_TERTIARY'; did you mean 'HWC_DISPLAY_P
RIMARY'?

Patch-set: 1