Update patch set 1
Patch Set 1:

build broken for non-qcom because of https://github.com/CyanogenMod/android_frameworks_native/commit/a18446321f55e05a845263baadc62fed48305b2e.

error: 'HWC_EVENT_ORIENTATION' was not declared in this scope

Patch-set: 1
Reviewer: Daniel Hillenbrand <523@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0