Update patch set 1
Patch Set 1:

Getting the following error in my builds due to this commit:

device/qcom/common/power/power.c:205:14: error: use of undeclared identifier 'POWER_HINT_AUDIO'; did you mean 'POWER_HINT_LAUNCH'?

Patch-set: 1